# Generated by Django 6.0 on 2025-12-26 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(help_text="Asl ob'ektning ID raqami")),
                ('full_name', models.CharField(max_length=255)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text="Barcha ma'lumotlar lug'ati")),
                ('role', models.CharField(choices=[('mentor', 'Mentor'), ('admin', 'Admin')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arxivlangan Xodim',
            },
        ),
        migrations.CreateModel(
            name='ArchivedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(help_text="Asl ob'ektning ID raqami")),
                ('full_name', models.CharField(max_length=255)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text="Barcha ma'lumotlar lug'ati")),
                ('branch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arxivlangan Student',
            },
        ),
    ]
