# Generated by Django 6.0 on 2026-01-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivebase', '0002_archivedgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=100, null=True)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('karta', models.CharField(max_length=20, null=True)),
                ('month', models.DateField()),
                ('is_paid', models.BooleanField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
