# Generated by Django 6.0 on 2026-01-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivebase', '0003_paymentarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedstaff',
            name='branch_id',
            field=models.IntegerField(blank=True, help_text='Filial ID raqami', null=True),
        ),
    ]
