# Generated by Django 5.2.11 on 2026-03-08 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivebase', '0004_archivedstaff_branch_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentarchive',
            options={'verbose_name': "To'lov Arxivi"},
        ),
        migrations.CreateModel(
            name='ArchivedHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(help_text="Asl ob'ektning ID raqami")),
                ('full_name', models.CharField(max_length=255)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text="Barcha ma'lumotlar lug'ati")),
                ('group_id', models.IntegerField()),
                ('group_name', models.CharField(max_length=200)),
                ('mentor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('submission_stats', models.JSONField(default=dict, help_text='Talabalar statistikasi (snapshot)')),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arxivlangan Uyga Vazifa',
                'verbose_name_plural': 'Arxivlangan Uyga Vazifalar',
            },
        ),
    ]
