# Generated by Django 5.2.11 on 2026-03-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivebase', '0005_alter_paymentarchive_options_archivedhomework'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedhomework',
            name='item_type',
            field=models.CharField(choices=[('homework', 'Uyga Vazifa'), ('mock_test', 'Mock Test')], default='homework', max_length=20),
        ),
    ]
