# Generated by Django 6.0.4 on 2026-05-18 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDownloadTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Excel Report'), ('monthly', 'Monthly Financial Report')], max_length=10, verbose_name='Hisobot turi')),
                ('report_date', models.DateField(verbose_name='Hisobot sanasi')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklab olingan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_downloads', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Hisobot yuklash tarixi',
                'verbose_name_plural': 'Hisobot yuklash tarixlari',
                'unique_together': {('user', 'report_type', 'report_date')},
            },
        ),
    ]
