# Generated by Django 6.0.4 on 2026-06-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdownloadtrack',
            name='report_type',
            field=models.CharField(choices=[('daily', 'Daily Excel Report'), ('monthly', 'Monthly Financial Report'), ('attendance_monthly', 'Monthly Attendance Report')], max_length=20, verbose_name='Hisobot turi'),
        ),
    ]
