# Generated by Django 6.0 on 2025-12-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_monthly_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='days',
            field=models.CharField(blank=True, choices=[('odd', 'Toq kunlar'), ('even', 'Juft kunlar'), ('everyday', 'Har kuni')], default='odd', max_length=10, null=True, verbose_name='Dars kunlari turi'),
        ),
    ]
