# Generated by Django 6.0 on 2026-02-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_student_telegram_id_alter_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_telegram_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Parent Telegram Chat ID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mentorgroupassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Student Telegram Chat ID'),
        ),
    ]
