# Generated by Django 5.2.11 on 2026-02-26 00:30

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_student_parent_telegram_id_alter_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='students/', validators=[config.validators.validate_image_file]),
        ),
    ]
