# Generated by Django 5.2.11 on 2026-03-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='custom_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Agar o'quvchi guruh narxidan boshqa (masalan, kamroq) narxda o'qisa, shu yerga yozing.", max_digits=10, null=True, verbose_name='Individual narx'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('regular', 'Oddiy'), ('discount', 'Imtiyozli'), ('low_income', "Kam ta'minlangan"), ('negotiated', 'Kelishilgan narx')], default='regular', max_length=20, verbose_name="O'quvchi holati"),
        ),
    ]
