# Generated by Django 5.2.11 on 2026-03-09 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_student_custom_fee_student_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('old_group_fee', models.DecimalField(decimal_places=2, help_text="Eski guruh uchun qolgan qarz/to'lov", max_digits=10)),
                ('new_group_fee', models.DecimalField(decimal_places=2, help_text="Yangi guruh uchun boshlang'ich to'lov", max_digits=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='groups.group')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='groups.student')),
                ('to_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='groups.group')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
