# Generated by Django 5.2.8 on 2026-04-04 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_grouptransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='groups.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='groups.student')),
            ],
            options={
                'verbose_name': "O'quvchi guruhga birikishi",
                'verbose_name_plural': "O'quvchilar guruhga birikishi",
                'unique_together': {('student', 'group')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(related_name='all_students', through='groups.GroupEnrollment', to='groups.group', verbose_name="O'quvchi guruhlari"),
        ),
    ]
