# Generated by Django 5.2.8 on 2026-04-04 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_groupenrollment_student_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_students_fk', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(related_name='students', through='groups.GroupEnrollment', to='groups.group', verbose_name="O'quvchi guruhlari"),
        ),
    ]
