# Generated by Django 5.2.8 on 2026-04-16 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_color'),
        ('groups', '0017_alter_student_group_alter_student_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ism Familiya')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qiziqqan fan')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_students', to='branches.branch')),
            ],
            options={
                'verbose_name': "Kutayotgan o'quvchi",
                'verbose_name_plural': "Kutayotgan o'quvchilar",
                'ordering': ['-created_at'],
            },
        ),
    ]
