# Generated by Django 6.0.4 on 2026-05-05 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_color'),
        ('groups', '0019_alter_student_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['branch', 'is_faol'], name='groups_grou_branch__f21673_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['mentor', 'is_faol'], name='groups_grou_mentor__81665e_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['start_date', 'days'], name='groups_grou_start_d_bf111c_idx'),
        ),
        migrations.AddIndex(
            model_name='groupenrollment',
            index=models.Index(fields=['student', 'is_active'], name='groups_grou_student_d080b4_idx'),
        ),
        migrations.AddIndex(
            model_name='groupenrollment',
            index=models.Index(fields=['group', 'is_active'], name='groups_grou_group_i_b15759_idx'),
        ),
    ]
