# Generated by Django 6.0.4 on 2026-05-06 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_group_groups_grou_branch__f21673_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialLessonDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_lesson_days', to='groups.group')),
            ],
            options={
                'verbose_name': "Qo'shimcha dars kuni",
                'verbose_name_plural': "Qo'shimcha dars kunlari",
                'ordering': ['-date'],
                'unique_together': {('group', 'date')},
            },
        ),
    ]
