# Generated by Django 6.0.4 on 2026-05-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0021_speciallessonday'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('standard', 'Standart'), ('advanced', 'Advanced')], default='standard', max_length=20, verbose_name='Guruh turi'),
        ),
    ]
