# Generated by Django 6.0.4 on 2026-05-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0022_group_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='include_in_mentor_salary',
            field=models.BooleanField(default=False, help_text="Faqat 'O'qituvchi kelishgan' statusidagi o'quvchilar uchun amal qiladi.", verbose_name="Mentor oyligiga qo'shilsinmi?"),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('regular', 'Oddiy'), ('discount', 'Imtiyozli'), ('low_income', "Kam ta'minlangan"), ('negotiated', 'Kelishilgan narx'), ('teacher_negotiated', "O'qituvchi kelishgan")], default='regular', max_length=20, verbose_name="O'quvchi holati"),
        ),
    ]
