# Generated by Django 6.0.4 on 2026-05-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0023_student_include_in_mentor_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingstudent',
            name='parent_telegram_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ota-ona Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='waitingstudent',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
