# Generated by Django 6.0.4 on 2026-05-29 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0024_waitingstudent_parent_telegram_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanceledLessonDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True, verbose_name='Bekor qilish sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canceled_lesson_days', to='groups.group')),
            ],
            options={
                'verbose_name': 'Bekor qilingan dars kuni',
                'verbose_name_plural': 'Bekor qilingan dars kunlari',
                'ordering': ['-date'],
                'unique_together': {('group', 'date')},
            },
        ),
    ]
