# Generated by Django 6.0.4 on 2026-05-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0025_canceledlessonday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='days',
            field=models.CharField(choices=[('odd', 'Toq kunlar'), ('even', 'Juft kunlar'), ('everyday', 'Har kuni')], default='odd', max_length=10, verbose_name='Dars kunlari turi'),
        ),
    ]
