# Generated by Django 6.0.4 on 2026-05-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0026_alter_group_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arxivlangan'),
        ),
        migrations.AddField(
            model_name='student',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arxivlangan'),
        ),
    ]
