# Generated by Django 6.0 on 2025-12-24 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-month'], 'verbose_name': "O'quvchi to'lovi", 'verbose_name_plural': "O'quvchilar to'lovlari"},
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_card_mask',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='marked_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'super_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_student_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmployeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('salary_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Asosiy maosh')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bonus')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ayirmalar')),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(limit_choices_to={'role__in': ['mentor', 'admin']}, on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'super_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_employee_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xodim maoshi',
                'verbose_name_plural': 'Xodimlar maoshlari',
                'ordering': ['-month'],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
