# Generated by Django 6.0 on 2025-12-24 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_payment_options_payment_payer_card_mask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Oylik maosh (so'mda)")),
                ('user', models.OneToOneField(limit_choices_to={'role__in': ['mentor', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xodim profili',
                'verbose_name_plural': 'Xodimlar profillari',
            },
        ),
    ]
