# Generated by Django 6.0 on 2026-01-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='karta',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
    ]
