# Generated by Django 6.0 on 2026-01-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_staffprofile_karta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='monthly_salary',
            new_name='salary_base',
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Bonus'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Ayirmalar'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='salary_base',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Asosiy maosh'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='karta',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True),
        ),
    ]
