# Generated by Django 6.0 on 2026-01-04 09:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_rename_monthly_salary_staffprofile_salary_base_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='salary_base',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Faqat 'Foiz asosida' turida ishlatiladi", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Komissiya foizi (%)'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Yaratilgan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='fixed_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Faqat 'Belgilangan oylik' turida ishlatiladi", max_digits=12, verbose_name="Belgilangan maosh (so'm)"),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='salary_type',
            field=models.CharField(choices=[('fixed', "Belgilangan oylik (so'm)"), ('percentage', 'Foiz asosida (%)')], default='fixed', max_length=20, verbose_name='Maosh turi'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name="To'landi"),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='marked_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'super_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_employee_payments', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan tasdiqlandi'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='month',
            field=models.DateField(verbose_name='Oy'),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'langan vaqt"),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='karta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Karta raqami'),
        ),
    ]
