# Generated by Django 6.0 on 2026-01-25 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_color'),
        ('finance', '0006_remove_staffprofile_salary_base_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Tushum (Kirim)'), ('expense', 'Chiqim (Chiqit)')], db_index=True, max_length=10)),
                ('category', models.CharField(choices=[('student_fee', "O'quvchi to'lovi"), ('salary', 'Xodim maoshi'), ('utility', "Kommunal to'lovlar"), ('rent', 'Ijara'), ('other', 'Boshqa')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(db_index=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('related_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='branches.branch')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moliya operatsiyasi',
                'verbose_name_plural': 'Moliya operatsiyalari',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date', 'transaction_type'], name='finance_fin_date_6ba9ed_idx'), models.Index(fields=['branch', 'transaction_type'], name='finance_fin_branch__8138e9_idx')],
            },
        ),
    ]
