# Generated by Django 5.2.11 on 2026-03-08 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_financetransaction'),
        ('groups', '0014_student_custom_fee_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='groups.group'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='payer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='groups.student'),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='category',
            field=models.CharField(choices=[('student_fee', "O'quvchi to'lovi"), ('salary', 'Xodim maoshi'), ('utility', "Kommunal to'lovlar"), ('rent', 'Ijara'), ('refund', 'Qaytarilgan pul (Dars qoldirgani uchun)'), ('student_extra', "O'quvchi qo'shimcha to'lovi"), ('other', 'Boshqa')], db_index=True, max_length=20),
        ),
    ]
