# Generated by Django 5.2.8 on 2026-04-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_financetransaction_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_ignored',
            field=models.BooleanField(default=False, verbose_name='Refund bekor qilingan'),
        ),
    ]
