# Generated by Django 6.0.4 on 2026-04-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_payment_refund_ignored'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='per_student_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Faqat 'O'quvchilar soni bo'yicha' turida ishlatiladi", max_digits=12, verbose_name="Har bir o'quvchi uchun (so'm)"),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='salary_type',
            field=models.CharField(choices=[('fixed', "Belgilangan oylik (so'm)"), ('percentage', 'Foiz asosida (%)'), ('student_count', "O'quvchilar soni bo'yicha (so'm/o'quvchi)")], default='fixed', max_length=20, verbose_name='Maosh turi'),
        ),
    ]
