# Generated by Django 5.2.8 on 2026-04-16 16:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_staffprofile_per_student_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Qaysi oy maoshidan ayriladi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Avans summasi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Berilgan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_advances', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim berdi')),
            ],
            options={
                'verbose_name': 'Xodim avansi',
                'verbose_name_plural': 'Xodimlar avanslari',
                'ordering': ['-date'],
            },
        ),
    ]
