# Generated by Django 6.0.4 on 2026-04-25 17:28

import django.db.models.deletion
from django.db import migrations, models


def cleanup_null_student_payments(apps, schema_editor):
    """
    Legacy bazada student=NULL bo'lgan paymentlar qolgan.
    0013 da student ni NOT NULL qilishdan oldin ularni tozalaymiz.
    """
    Payment = apps.get_model('finance', 'Payment')
    Payment.objects.filter(student__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_payment_group_alter_payment_student'),
        ('groups', '0019_alter_student_group'),
    ]

    operations = [
        migrations.RunPython(cleanup_null_student_payments, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='groups.student'),
        ),
    ]
