# Generated by Django 6.0.4 on 2026-05-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_payment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_receiptless',
            field=models.BooleanField(default=False, verbose_name="Chek yo'q"),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('click', 'Click / Card'), ('payme', 'Payme'), ('other', 'Boshqa')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
