# Generated by Django 6.0.4 on 2026-05-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_payment_is_verified_payment_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayment',
            name='attendance_deductions',
            field=models.JSONField(blank=True, default=dict, help_text="Har bir o'quvchi uchun davomat sababli qirqilgan summa tafsilotlari", verbose_name="Davomat bo'yicha ayirmalar"),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='category',
            field=models.CharField(choices=[('student_fee', "O'quvchi to'lovi"), ('salary', 'Xodim maoshi'), ('utility', "Kommunal to'lovlar"), ('rent', 'Ijara'), ('refund', 'Qaytarilgan pul (Dars qoldirgani uchun)'), ('student_extra', "O'quvchi qo'shimcha to'lovi"), ('owner_withdrawal', 'Super Admin olib ketdi'), ('other', 'Boshqa')], db_index=True, max_length=20),
        ),
    ]
