# Generated by Django 6.0.4 on 2026-05-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_payment_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_full_amount',
            field=models.BooleanField(default=False, verbose_name="To'liq oylik to'langan"),
        ),
    ]
