# Generated by Django 6.0.4 on 2026-05-14 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_color'),
        ('finance', '0018_payment_is_full_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Harajat nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tafsilotlar')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('date', models.DateField(db_index=True, verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_expenses', to='branches.branch', verbose_name='Filial')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kiritdi')),
            ],
            options={
                'verbose_name': 'Admin harajati',
                'verbose_name_plural': 'Admin harajatlari',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
