# Generated by Django 6.0.4 on 2026-05-29 17:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_payment_paid_amount_is_partial'),
        ('groups', '0026_alter_group_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorGroupSalaryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(choices=[('percentage', 'Foiz asosida (%)'), ('student_count', "O'quvchilar soni bo'yicha (so'm/o'quvchi)")], max_length=20, verbose_name='Maosh turi')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, help_text="Faqat 'Foiz asosida' turida ishlatiladi", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Komissiya foizi (%)')),
                ('per_student_amount', models.DecimalField(decimal_places=2, default=0, help_text="Faqat 'O'quvchilar soni bo'yicha' turida ishlatiladi", max_digits=12, verbose_name="Har bir o'quvchi uchun (so'm)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_salary_configs', to='groups.group', verbose_name='Guruh')),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='group_salary_configs', to=settings.AUTH_USER_MODEL, verbose_name='Mentor')),
            ],
            options={
                'verbose_name': 'Guruh uchun mentor maoshi konfiguratsiyasi',
                'verbose_name_plural': 'Guruhlar uchun mentor maoshi konfiguratsiyalari',
                'unique_together': {('mentor', 'group')},
            },
        ),
    ]
