# Generated by Django 6.0.4 on 2026-07-15 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_alter_payment_unique_together_payment_group_name_and_more'),
        ('groups', '0028_group_groups_grou_name_0806de_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFinanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_paid_all_time', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Jami to'lagan (hayoti davomida)")),
                ('total_refunded', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami qaytarilgan (refunds)')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name="Oxirgi to'lov sanasi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_profile', to='groups.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "O'quvchi Moliyaviy Profili (Wallet)",
                'verbose_name_plural': "O'quvchilar Moliyaviy Profillari",
            },
        ),
    ]
