# Generated by Django 6.0.4 on 2026-07-22 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_color'),
        ('finance', '0024_studentfinanceprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financetransaction',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='branches.branch'),
        ),
    ]
