# Generated by Django 6.0.4 on 2026-07-23 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_color'),
        ('finance', '0025_fix_transaction_branch_cascade_to_protect'),
        ('groups', '0028_group_groups_grou_name_0806de_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfinanceprofile',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='studentfinanceprofile',
            name='total_paid_all_time',
        ),
        migrations.RemoveField(
            model_name='studentfinanceprofile',
            name='total_refunded',
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='record_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('reversal', 'Reversal'), ('refund', 'Refund')], db_index=True, default='payment', max_length=20),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='related_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='finance.financetransaction'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='completed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='financetransaction',
            index=models.Index(fields=['status', 'record_type'], name='finance_fin_status_c1c931_idx'),
        ),
    ]
