# Generated by Django 6.0.4 on 2026-07-26 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_color'),
        ('finance', '0026_remove_studentfinanceprofile_last_payment_date_and_more'),
        ('groups', '0028_group_groups_grou_name_0806de_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text="True bo'lsa, bu tranzaksiya global balansga qo'shilgan hisoblanadi.", verbose_name='Kassa tasdiqlagani'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='financetransaction',
            index=models.Index(fields=['is_verified', 'transaction_type'], name='finance_fin_is_veri_09f919_idx'),
        ),
        migrations.AddIndex(
            model_name='financetransaction',
            index=models.Index(fields=['branch', 'is_verified'], name='finance_fin_branch__c65dda_idx'),
        ),
    ]
