# Generated by Django 6.0.4 on 2026-07-26 09:50

from django.db import migrations
from django.utils import timezone

def set_historical_data_verified(apps, schema_editor):
    FinanceTransaction = apps.get_model('finance', 'FinanceTransaction')
    Payment = apps.get_model('finance', 'Payment')

    # Barcha eski tranzaksiyalar (chunki ular eski kassa logikasi bilan to'g'ridan-to'g'ri o'tgan)
    FinanceTransaction.objects.update(
        is_verified=True,
        verified_at=timezone.now()
    )

    # Allaqachon to'langan yoki qisman to'langan to'lovlar ham tasdiqlangan hisoblanadi
    Payment.objects.filter(is_paid=True).update(
        is_verified=True,
        verified_at=timezone.now()
    )
    Payment.objects.filter(is_partial=True).update(
        is_verified=True,
        verified_at=timezone.now()
    )

def reverse_historical_data_verified(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_financetransaction_is_verified'),
    ]

    operations = [
        migrations.RunPython(set_historical_data_verified, reverse_historical_data_verified),
    ]
