# Generated by Django 6.0.4 on 2026-08-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_set_historical_data_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_auto_discount',
            field=models.BooleanField(default=False, help_text="True bo'lsa, bu invoice discount o'quvchi uchun avtomatik yaratilgan va StudentFinanceProfile.balance hisobiga kiritilmaydi.", verbose_name='Imtiyozli (avtomatik) invoice'),
        ),
    ]
