# Generated by Django 6.0.4 on 2026-08-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_payment_is_auto_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Guruh nomi (Snapshot)'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="O'quvchi ismi (Snapshot)"),
        ),
    ]
