# Generated by Django 6.0.4 on 2026-08-02 08:26

from django.db import migrations


def backfill_snapshots(apps, schema_editor):
    FinanceTransaction = apps.get_model('finance', 'FinanceTransaction')
    Payment = apps.get_model('finance', 'Payment')
    
    for tx in FinanceTransaction.objects.all():
        student_name = None
        group_name = None
        
        # 1. Relations
        if tx.student:
            student_name = tx.student.full_name
        if tx.group:
            group_name = tx.group.name
            
        # 2. Payment snapshot (if relational is None)
        if (not student_name or not group_name) and tx.category == 'student_fee' and tx.related_id and tx.related_id.startswith('STP-'):
            parts = tx.related_id.split('-')
            if len(parts) >= 2:
                try:
                    payment_id = int(parts[1])
                    payment = Payment.objects.filter(id=payment_id).first()
                    if payment:
                        if not student_name:
                            student_name = payment.student_full_name
                        if not group_name:
                            group_name = payment.group_name
                except ValueError:
                    pass
                    
        # 3. Fallbacks
        if not student_name:
            if tx.payer_name:
                student_name = tx.payer_name
            elif tx.title and "To'lov:" in tx.title:
                student_name = tx.title.replace("To'lov:", "").strip()
            elif tx.title and "Refund:" in tx.title:
                student_name = tx.title.replace("Refund:", "").strip()
                
        tx.student_name = student_name
        tx.group_name = group_name
        tx.save(update_fields=['student_name', 'group_name'])

def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_financetransaction_snapshots'),
    ]

    operations = [
        migrations.RunPython(backfill_snapshots, reverse_backfill),
    ]
