# Generated by Django 6.0.4 on 2026-08-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_backfill_transaction_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="To'lov usuli (Snapshot)"),
        ),
    ]
