# Generated by Django 6.0 on 2026-01-12 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message="Xato format! Rang #ffffff kabi bo'lishi kerak.", regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
    ]
