# Generated by Django 6.0.4 on 2026-05-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticatsiya', '0004_alter_usermodel_managers_usermodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('mentor', 'Mentor')], default='mentor', max_length=15),
        ),
    ]
