# Generated by Django 6.0.4 on 2026-07-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticatsiya', '0005_alter_usermodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID (Admin Bot)'),
        ),
    ]
