# Generated by Django 6.0.8 on 2026-09-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticatsiya', '0006_usermodel_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('mentor', 'Mentor'), ('student', 'Student')], default='mentor', max_length=15),
        ),
    ]
