# Generated by Django 6.0.8 on 2026-09-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticatsiya', '0007_alter_usermodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_portfolio_public',
            field=models.BooleanField(default=True),
        ),
    ]
