# Generated by Django 6.0.8 on 2026-09-18 22:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('schedule', models.CharField(default='Dush / Chor / Juma • 16:00', max_length=255)),
                ('max_students', models.PositiveSmallIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_study_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'curriculum_study_group',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyGroupStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('ai_score', models.CharField(default='Yangi', max_length=50)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='curriculum.studygroup')),
            ],
            options={
                'db_table': 'curriculum_study_group_student',
                'ordering': ['-joined_date'],
            },
        ),
    ]
