# Generated by Django 6.0.8 on 2026-09-19 00:31

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_course_is_published_alter_lesson_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='attachment',
            field=models.FileField(blank=True, help_text="Dars uchun qo'shimcha material: PDF, DOCX, JPG, PNG (max 20MB)", null=True, upload_to=curriculum.models.lesson_attachment_path, validators=[curriculum.models.validate_lesson_file]),
        ),
        migrations.AddField(
            model_name='lesson',
            name='attachment_name',
            field=models.CharField(blank=True, help_text='Original fayl nomi', max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Lesson content in Markdown. Used as RAG knowledge base.'),
        ),
    ]
