// Mendeleyev Davriy Jadvali (Periodic Table of Elements) Data
export const PERIODIC_ELEMENTS = [
  { number: 1, symbol: "H", name: "Vodorod", mass: "1.008", group: 1, period: 1, category: "nonmetal", valence: 1, desc: "Koinotdagi eng yengil va eng ko'p tarqalgan gaz." },
  { number: 2, symbol: "He", name: "Geliy", mass: "4.0026", group: 18, period: 1, category: "noble", valence: 0, desc: "Inert gaz, reaksiyaga kirishmaydi, yengil." },
  { number: 3, symbol: "Li", name: "Litiy", mass: "6.94", group: 1, period: 2, category: "alkali", valence: 1, desc: "Eng yengil ishqoriy metall, suv bilan kuchli ta'sirlashadi." },
  { number: 4, symbol: "Be", name: "Berilliy", mass: "9.0122", group: 2, period: 2, category: "alkaline", valence: 2, desc: "Mustahkam va yengil ishqoriy-yer metalli." },
  { number: 5, symbol: "B", name: "Bor", mass: "10.81", group: 13, period: 2, category: "metalloid", valence: 3, desc: "Yarim metall, shisha va kislotalar tarkibida uchraydi." },
  { number: 6, symbol: "C", name: "Uglerod", mass: "12.011", group: 14, period: 2, category: "nonmetal", valence: 4, desc: "Organik hayotning asosi, olmos va grafit hosil qiladi." },
  { number: 7, symbol: "N", name: "Azot", mass: "14.007", group: 15, period: 2, category: "nonmetal", valence: 3, desc: "Atmosferaning 78% qismini tashkil qiluvchi rangsiz gaz." },
  { number: 8, symbol: "O", name: "Kislorod", mass: "15.999", group: 16, period: 2, category: "nonmetal", valence: 2, desc: "Nafas olish va yonish uchun zarur kuchli oksidlovchi gaz." },
  { number: 9, symbol: "F", name: "Ftor", mass: "18.998", group: 17, period: 2, category: "halogen", valence: 1, desc: "Eng kuchli elektr-manfiy kimyoviy element, o'ta faol galogen." },
  { number: 10, symbol: "Ne", name: "Neon", mass: "20.180", group: 18, period: 2, category: "noble", valence: 0, desc: "Inert gaz, elektr razryadida qizil-to'q sariq nur taratadi." },
  { number: 11, symbol: "Na", name: "Natriy", mass: "22.990", group: 1, period: 3, category: "alkali", valence: 1, desc: "Yumshoq ishqoriy metall, suvda vodorod ajratib shiddatli reaksiyaga kirishadi." },
  { number: 12, symbol: "Mg", name: "Magniy", mass: "24.305", group: 2, period: 3, category: "alkaline", valence: 2, desc: "Kumushsimon yengil metall, havoda oq alanga bilan yonadi." },
  { number: 13, symbol: "Al", name: "Alyuminiy", mass: "26.982", group: 13, period: 3, category: "post-transition", valence: 3, desc: "Amfoter metall, korroziyaga chidamli, aviatsiyada keng qo'llaniladi." },
  { number: 14, symbol: "Si", name: "Kremniy", mass: "28.085", group: 14, period: 3, category: "metalloid", valence: 4, desc: "Yarimo'tkazgich, mikrochiplar va shisha asosiy asosi." },
  { number: 15, symbol: "P", name: "Fosfor", mass: "30.974", group: 15, period: 3, category: "nonmetal", valence: 5, desc: "DNK, suyaklar va gugurt tayyorlashda ishlatiladi." },
  { number: 16, symbol: "S", name: "Oltingugurt", mass: "32.06", group: 16, period: 3, category: "nonmetal", valence: 6, desc: "Sariq kristall modda, sulfat kislota ishlab chiqarishda ishlatiladi." },
  { number: 17, symbol: "Cl", name: "Xlor", mass: "35.45", group: 17, period: 3, category: "halogen", valence: 1, desc: "O'tkir hidli, sarg'ish-yashil zaharli galogen gaz." },
  { number: 18, symbol: "Ar", name: "Argon", mass: "39.948", group: 18, period: 3, category: "noble", valence: 0, desc: "Inert gaz, payvandlashda va lampalarda himoya muhiti yaratadi." },
  { number: 19, symbol: "K", name: "Kaliy", mass: "39.098", group: 1, period: 4, category: "alkali", valence: 1, desc: "O'ta faol ishqoriy metall, o'simliklar ozuqasi va elektrolit." },
  { number: 20, symbol: "Ca", name: "Kalsiy", mass: "40.078", group: 2, period: 4, category: "alkaline", valence: 2, desc: "Suyak va tishlarning asosiy mineral quruvchi elementi." },
  { number: 21, symbol: "Sc", name: "Skandiy", mass: "44.956", group: 3, period: 4, category: "transition", valence: 3, desc: "Yengil qotishmalar tayyorlashda ishlatiladigan o'tish metalli." },
  { number: 22, symbol: "Ti", name: "Titan", mass: "47.867", group: 4, period: 4, category: "transition", valence: 4, desc: "O'ta pishiq, yengil va korroziyaga bardoshli fazoviy metall." },
  { number: 23, symbol: "V", name: "Vanadiy", mass: "50.942", group: 5, period: 4, category: "transition", valence: 5, desc: "Po'lat qotishmalarini mustahkamlovchi o'tish metalli." },
  { number: 24, symbol: "Cr", name: "Xrom", mass: "51.996", group: 6, period: 4, category: "transition", valence: 6, desc: "Yaltiroq, qattiq, zanglamas po'lat tarkibiga kiradi." },
  { number: 25, symbol: "Mn", name: "Marganets", mass: "54.938", group: 7, period: 4, category: "transition", valence: 7, desc: "Kaliy permanganat (margantsovka) tarkibidagi kuchli oksidlovchi." },
  { number: 26, symbol: "Fe", name: "Temir", mass: "55.845", group: 8, period: 4, category: "transition", valence: 3, desc: "Insoniyat sivilizatsiyasi asosi, gemoglobin yadrosi." },
  { number: 27, symbol: "Co", name: "Kobalt", mass: "58.933", group: 9, period: 4, category: "transition", valence: 2, desc: "Magnitlar va vitamin B12 tarkibiy qismi." },
  { number: 28, symbol: "Ni", name: "Nikel", mass: "58.693", group: 10, period: 4, category: "transition", valence: 2, desc: "Korroziyaga chidamli, tangalar va akkumulyatorlar tayyorlashda ishlatiladi." },
  { number: 29, symbol: "Cu", name: "Mis", mass: "63.546", group: 11, period: 4, category: "transition", valence: 2, desc: "Yuqori elektr va issiqlik o'tkazuvchi qizg'ish metall." },
  { number: 30, symbol: "Zn", name: "Rux", mass: "65.38", group: 12, period: 4, category: "transition", valence: 2, desc: "Temirni galvanizatsiyalash va kislotalardan vodorod olishda qo'llaniladi." },
  { number: 35, symbol: "Br", name: "Brom", mass: "79.904", group: 17, period: 4, category: "halogen", valence: 1, desc: "Xona haroratidagi yagona suyuq qizil-jigarrang nometall." },
  { number: 47, symbol: "Ag", name: "Kumush", mass: "107.87", group: 11, period: 5, category: "transition", valence: 1, desc: "Eng yuqori elektr o'tkazuvchi oliy metall, antibakterial." },
  { number: 50, symbol: "Sn", name: "Qalay", mass: "118.71", group: 14, period: 5, category: "post-transition", valence: 4, desc: "Yumshoq korroziyaga chidamli lehim metalli." },
  { number: 53, symbol: "I", name: "Yod", mass: "126.90", group: 17, period: 5, category: "halogen", valence: 1, desc: "Binafsharang bug' chiqaruvchi qora kristallar, tibbiy antiseptik." },
  { number: 56, symbol: "Ba", name: "Bariy", mass: "137.33", group: 2, period: 6, category: "alkaline", valence: 2, desc: "Og'ir ishqoriy-yer metalli, rentgen tahlilida kontrast modda." },
  { number: 79, symbol: "Au", name: "Oltin", mass: "196.97", group: 11, period: 6, category: "transition", valence: 3, desc: "Kimyoviy reaksiyalarga deyarli kirmaydigan oliy sariq metall." },
  { number: 80, symbol: "Hg", name: "Simob", mass: "200.59", group: 12, period: 6, category: "transition", valence: 2, desc: "Xona haroratidagi yagona og'ir suyuq metall, o'ta zaharli bug'lanadi." },
  { number: 82, symbol: "Pb", name: "Qo'rg'oshin", mass: "207.2", group: 14, period: 6, category: "post-transition", valence: 2, desc: "Zich, og'ir metall, radiatsiya va rentgen nurlaridan himoya qiladi." }
];

export const CATEGORY_COLORS = {
  nonmetal: { bg: "bg-emerald-500/20", border: "border-emerald-500/40", text: "text-emerald-700 dark:text-emerald-300", label: "Nometallar" },
  noble: { bg: "bg-purple-500/20", border: "border-purple-500/40", text: "text-purple-700 dark:text-purple-300", label: "Inert gazlar" },
  alkali: { bg: "bg-rose-500/20", border: "border-rose-500/40", text: "text-rose-700 dark:text-rose-300", label: "Ishqoriy metallar" },
  alkaline: { bg: "bg-amber-500/20", border: "border-amber-500/40", text: "text-amber-700 dark:text-amber-300", label: "Ishqoriy-yer metallar" },
  metalloid: { bg: "bg-teal-500/20", border: "border-teal-500/40", text: "text-teal-700 dark:text-teal-300", label: "Yarim metallar" },
  halogen: { bg: "bg-cyan-500/20", border: "border-cyan-500/40", text: "text-cyan-700 dark:text-cyan-300", label: "Galogenlar" },
  transition: { bg: "bg-blue-500/20", border: "border-blue-500/40", text: "text-blue-700 dark:text-blue-300", label: "O'tish metallari" },
  "post-transition": { bg: "bg-indigo-500/20", border: "border-indigo-500/40", text: "text-indigo-700 dark:text-indigo-300", label: "Qo'shimcha metallar" },
};
