# Generated by Django 6.0 on 2025-12-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_attends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworksubmission',
            options={},
        ),
        migrations.RemoveField(
            model_name='homework',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='is_submitted',
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='status',
            field=models.CharField(choices=[('not_submitted', 'Topshirmagan'), ('half', 'Yarim topshirgan'), ('full', 'To‘liq topshirgan')], default='not_submitted', max_length=20),
        ),
    ]
