# Generated by Django 6.0 on 2025-12-21 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_monthly_price'),
        ('homework_attends', '0003_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'student__full_name']},
        ),
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_attendance_per_student_per_day',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='homework_at_group_i_78b1fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='homework_at_student_922469_idx',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'group', 'date')},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='marked_at',
        ),
    ]
