# Generated by Django 6.0 on 2026-02-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_attends', '0006_rename_subject_mocktest_title_alter_attendance_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mocktest',
            old_name='title',
            new_name='subject',
        ),
    ]
