# Generated by Django 5.2.11 on 2026-03-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_attends', '0007_rename_title_mocktest_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='last_sent_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
