# Generated by Django 5.2.8 on 2026-04-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_attends', '0008_attendance_last_sent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
    ]
