# Generated by Django 6.0.4 on 2026-07-15 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_attends', '0010_alter_attendance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.BooleanField()),
                ('new_status', models.BooleanField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='homework_attends.attendance')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Davomat tahrir tarixi',
                'verbose_name_plural': 'Davomat tahrir tarixlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
