# Generated by Django 6.0.4 on 2026-07-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_attends', '0011_attendanceeditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceeditlog',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
