# Generated by Django 6.0.4 on 2026-07-10 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0028_group_groups_grou_name_0806de_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Telegram ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('language', models.CharField(default='uz', max_length=10, verbose_name='Til')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_profile', to='groups.student')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot Foydalanuvchisi',
                'verbose_name_plural': 'Bot Foydalanuvchilari',
            },
        ),
    ]
