# Generated by Django 6.0.8 on 2026-09-18 15:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(help_text='Scenario presented to the student.')),
                ('role_context', models.TextField(help_text='The role the student assumes.')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('EXPERT', 'Expert')], db_index=True, default='MEDIUM', max_length=10)),
                ('coin_reward', models.PositiveIntegerField(default=25)),
                ('max_steps', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(50)])),
                ('passing_score', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grading_rubric', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_cases', to='curriculum.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_simulation_cases', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_cases', to='curriculum.lesson')),
            ],
            options={
                'db_table': 'simulation_case',
                'ordering': ['course', 'difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SimulationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ABANDONED', 'Abandoned')], db_index=True, default='ACTIVE', max_length=20)),
                ('current_step', models.PositiveSmallIntegerField(default=0)),
                ('steps_taken', models.PositiveSmallIntegerField(default=0)),
                ('total_score', models.FloatField(default=0.0)),
                ('error_analysis', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='simulation.simulationcase')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'simulation_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationStepLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveSmallIntegerField()),
                ('student_input', models.TextField()),
                ('ai_response_raw', models.JSONField(default=dict)),
                ('step_score', models.FloatField(default=0.0)),
                ('feedback_text', models.TextField(blank=True)),
                ('next_scenario_text', models.TextField(blank=True)),
                ('is_final_step', models.BooleanField(default=False)),
                ('rag_context_chunks', models.JSONField(blank=True, default=list)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_logs', to='simulation.simulationsession')),
            ],
            options={
                'db_table': 'simulation_step_log',
                'ordering': ['session', 'step_number'],
                'unique_together': {('session', 'step_number')},
            },
        ),
    ]
