# Generated by Django 6.0.8 on 2026-09-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationcase',
            name='expected_duration_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='simulationcase',
            name='hint_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
