# Generated by Django 6.0.8 on 2026-09-19 01:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_simulationcase_expected_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationcase',
            name='max_participants',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='simulationcase',
            name='reaction_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Science or logic reaction matrix'),
        ),
        migrations.AddField(
            model_name='simulationcase',
            name='roles_schema',
            field=models.JSONField(blank=True, default=list, help_text='List of roles in this simulation room'),
        ),
        migrations.AddField(
            model_name='simulationcase',
            name='room_style',
            field=models.CharField(choices=[('COURTROOM', 'Sud Zali (Sudya, Prokuror, Advokat, Guvoh)'), ('CHEMISTRY_LAB', 'Kimyo Laboratoriyasi (Bosh Laborant, Reagent Tahlilchisi, Xavfsizlik Inspektori)'), ('MEDICAL_ER', 'Tibbiy Reanimatsiya (Bosh Shifokor, Jarroh, Anesteziolog)'), ('CYBER_DEFENSE', 'Kiber-Xavfsizlik Markazi (SOC Tahlilchi, Administrator, Kriptograf)'), ('CUSTOM', 'Umumiy / Erkin Simulyatsiya')], db_index=True, default='CUSTOM', max_length=30),
        ),
        migrations.CreateModel(
            name='SimulationRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('WAITING', 'Ishtirokchilar kutilmoqda'), ('ACTIVE', 'Jarayon faol'), ('COMPLETED', 'Yakunlandi')], db_index=True, default='WAITING', max_length=20)),
                ('max_participants', models.PositiveSmallIntegerField(default=4)),
                ('current_step', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='simulation.simulationcase')),
            ],
            options={
                'db_table': 'simulation_room',
                'ordering': ['case', 'room_number'],
                'unique_together': {('case', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='RoomChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_role', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=255)),
                ('is_ai', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('scientific_feedback', models.JSONField(blank=True, default=dict)),
                ('step_number', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='simulation.simulationroom')),
            ],
            options={
                'db_table': 'simulation_room_chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_id', models.CharField(max_length=100)),
                ('role_title', models.CharField(max_length=255)),
                ('role_goal', models.TextField(blank=True)),
                ('is_ai', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('individual_score', models.FloatField(default=0.0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_participations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='simulation.simulationroom')),
            ],
            options={
                'db_table': 'simulation_room_participant',
                'ordering': ['joined_at'],
                'unique_together': {('room', 'role_id')},
            },
        ),
    ]
